fraud:
  outputs:
    dev:
      account: 
      database: AIRBYTE_DATABASE
      password: airbyte
      role: AIRBYTE_ROLE
      schema: prod
      threads: 1
      type: snowflake
      user: AIRBYTE_USER
      warehouse: AIRBYTE_WAREHOUSE
  target: dev
